#!/usr/bin/env bash
# Prints holberton school except for bad luck 4 and  good luck 8.
i=0
while [ $((i++)) -lt 10 ]; do
	if [ $i -eq 4 ]; then
		echo bad luck
	elif [ $i -eq 8 ]; then
		echo good luck
	else
		echo Holberton School
	fi
done
